import { hexToHslString } from '../utils/color-converter';

/**
 * Generate globals.css file with theme colors and utilities
 * Direct generation - NO AI
 * Extracted from main frontend node for better maintainability
 */
export function generateGlobalsCss(stylingConfig: any): string {
  const colors = stylingConfig?.colorTheme;
  const mode = colors?.mode || 'light';
  const typography = stylingConfig?.typography;
  const headingWeight = typography?.headingWeight || 700;
  const fontFamily = typography?.fontFamily || 'Inter';
  const animations = stylingConfig?.animations || { enabled: true, intensity: 'subtle' };
  const layout = stylingConfig?.layout || {};
  const borderRadius = layout?.borderRadius || 'medium';

  // Border radius mapping
  const radiusMap: Record<string, string> = {
    none: '0',
    small: '0.25rem',
    medium: '0.5rem',
    large: '1rem',
    full: '9999px',
  };
  const radiusValue = radiusMap[borderRadius] || '0.5rem';

  // Convert hex colors to HSL strings for Tailwind
  const primaryHSL = colors?.primary ? hexToHslString(colors.primary) : '221.2 83.2% 53.3%';
  const secondaryHSL = colors?.secondary ? hexToHslString(colors.secondary) : '210 40% 96.1%';
  const accentHSL = colors?.accent ? hexToHslString(colors.accent) : '217.2 91.2% 59.8%';
  const backgroundHSL = colors?.background
    ? hexToHslString(colors.background)
    : mode === 'dark'
      ? '222.2 84% 4.9%'
      : '0 0% 100%';
  const backgroundSecondaryHSL = colors?.backgroundSecondary
    ? hexToHslString(colors.backgroundSecondary)
    : mode === 'dark'
      ? '222.2 84% 8%'
      : '0 0% 98%';
  const backgroundTertiaryHSL = colors?.backgroundTertiary
    ? hexToHslString(colors.backgroundTertiary)
    : mode === 'dark'
      ? '222.2 84% 11%'
      : '0 0% 96%';
  const borderHSL = colors?.border
    ? hexToHslString(colors.border)
    : mode === 'dark'
      ? '240 3.7% 15.9%'
      : '240 5.9% 90%';
  const mutedHSL = colors?.muted
    ? hexToHslString(colors.muted)
    : mode === 'dark'
      ? '240 3.7% 15.9%'
      : '240 4.8% 95.9%';
  const destructiveHSL = colors?.destructive ? hexToHslString(colors.destructive) : '0 84.2% 60.2%';
  const successHSL = colors?.success ? hexToHslString(colors.success) : '142.1 76.2% 36.3%';
  const warningHSL = colors?.warning ? hexToHslString(colors.warning) : '32.1 94.6% 43.7%';
  const infoHSL = colors?.info ? hexToHslString(colors.info) : '221.2 83.2% 53.3%';

  console.log('[Frontend] 🎨 Generating globals.css with colors:', {
    primary: colors?.primary ? `${colors.primary} → ${primaryHSL}` : 'default',
    mode,
    fontFamily,
    borderRadius,
    animationIntensity: animations.intensity,
  });

  const globalsCss = `/**
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by the VB platform based on your theme settings.
 * Any manual changes will be overwritten when you update your project's styling.
 * To modify styles, use Tailwind utility classes in your components.
 */

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    /* ========== BASE COLORS ========== */
    --background: ${backgroundHSL};
    --background-secondary: ${backgroundSecondaryHSL};
    --background-tertiary: ${backgroundTertiaryHSL};
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: ${primaryHSL};
    --primary-foreground: 210 40% 98%;
    --secondary: ${secondaryHSL};
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: ${mutedHSL};
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: ${accentHSL};
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: ${destructiveHSL};
    --destructive-foreground: 210 40% 98%;
    --success: ${successHSL};
    --success-foreground: 210 40% 98%;
    --warning: ${warningHSL};
    --warning-foreground: 222.2 84% 4.9%;
    --info: ${infoHSL};
    --info-foreground: 210 40% 98%;
    --border: ${borderHSL};
    --input: ${borderHSL};
    --ring: ${primaryHSL};
    --radius: ${radiusValue};${
      stylingConfig?.enhancedColors?.semantic
        ? `

    /* ========== SEMANTIC COLORS (ENRICHED) ========== */
    --text-default: ${hexToHslString(stylingConfig.enhancedColors.semantic.textDefault)};
    --text-secondary: ${hexToHslString(stylingConfig.enhancedColors.semantic.textSecondary)};
    --text-disabled: ${hexToHslString(stylingConfig.enhancedColors.semantic.textDisabled)};
    --text-on-color: ${hexToHslString(stylingConfig.enhancedColors.semantic.textOnColor)};
    --bg-default: ${hexToHslString(stylingConfig.enhancedColors.semantic.bgDefault)};
    --bg-surface: ${hexToHslString(stylingConfig.enhancedColors.semantic.bgSurface)};
    --bg-elevated: ${hexToHslString(stylingConfig.enhancedColors.semantic.bgElevated)};
    --bg-overlay: ${stylingConfig.enhancedColors.semantic.bgOverlay};
    --border-default: ${hexToHslString(stylingConfig.enhancedColors.semantic.borderDefault)};
    --border-subtle: ${hexToHslString(stylingConfig.enhancedColors.semantic.borderSubtle)};
    --border-strong: ${hexToHslString(stylingConfig.enhancedColors.semantic.borderStrong)};
    --interactive: ${hexToHslString(stylingConfig.enhancedColors.semantic.interactive)};
    --interactive-hover: ${hexToHslString(stylingConfig.enhancedColors.semantic.interactiveHover)};
    --interactive-active: ${hexToHslString(stylingConfig.enhancedColors.semantic.interactiveActive)};`
        : ''
    }${
      stylingConfig?.enhancedColors?.shadows
        ? `

    /* ========== SHADOWS (ENRICHED) ========== */
    --shadow-sm: ${stylingConfig.enhancedColors.shadows.sm};
    --shadow-md: ${stylingConfig.enhancedColors.shadows.md};
    --shadow-lg: ${stylingConfig.enhancedColors.shadows.lg};
    --shadow-xl: ${stylingConfig.enhancedColors.shadows.xl};
    --shadow-2xl: ${stylingConfig.enhancedColors.shadows['2xl']};
    --shadow-inner: ${stylingConfig.enhancedColors.shadows.inner};`
        : ''
    }${
      stylingConfig?.spacing
        ? `

    /* ========== SPACING (ENRICHED) ========== */
    --spacing-0: ${stylingConfig.spacing.scale['0']};
    --spacing-1: ${stylingConfig.spacing.scale['1']};
    --spacing-2: ${stylingConfig.spacing.scale['2']};
    --spacing-3: ${stylingConfig.spacing.scale['3']};
    --spacing-4: ${stylingConfig.spacing.scale['4']};
    --spacing-6: ${stylingConfig.spacing.scale['6']};
    --spacing-8: ${stylingConfig.spacing.scale['8']};
    --spacing-12: ${stylingConfig.spacing.scale['12']};
    --spacing-16: ${stylingConfig.spacing.scale['16']};
    --spacing-24: ${stylingConfig.spacing.scale['24']};
    --container-max: ${stylingConfig.spacing.layout.containerMax};
    --section-padding: ${stylingConfig.spacing.layout.sectionPadding};
    --component-gap: ${stylingConfig.spacing.layout.componentGap};`
        : ''
    }${
      stylingConfig?.bordering
        ? `

    /* ========== BORDER RADIUS (ENRICHED) ========== */
    --radius-sm: ${stylingConfig.bordering.radiusScale.sm};
    --radius-md: ${stylingConfig.bordering.radiusScale.md};
    --radius-lg: ${stylingConfig.bordering.radiusScale.lg};
    --radius-xl: ${stylingConfig.bordering.radiusScale.xl};
    --radius-2xl: ${stylingConfig.bordering.radiusScale['2xl']};
    --radius-full: ${stylingConfig.bordering.radiusScale.full};`
        : ''
    }${
      stylingConfig?.transitions
        ? `

    /* ========== TRANSITIONS (ENRICHED) ========== */
    --duration-fast: ${stylingConfig.transitions.durations.fast};
    --duration-normal: ${stylingConfig.transitions.durations.normal};
    --duration-slow: ${stylingConfig.transitions.durations.slow};
    --ease-default: ${stylingConfig.transitions.easings.default};
    --ease-spring: ${stylingConfig.transitions.easings.spring};
    --z-modal: ${stylingConfig.transitions.zIndices.modal};
    --z-popover: ${stylingConfig.transitions.zIndices.popover};
    --z-toast: ${stylingConfig.transitions.zIndices.toast};`
        : ''
    }
  }

  .dark {
    --background: ${mode === 'dark' ? backgroundHSL : '222.2 84% 4.9%'};
    --background-secondary: ${mode === 'dark' ? backgroundSecondaryHSL : '222.2 84% 8%'};
    --background-tertiary: ${mode === 'dark' ? backgroundTertiaryHSL : '222.2 84% 11%'};
    --foreground: 210 40% 98%;
    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;
    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;
    --primary: ${primaryHSL};
    --primary-foreground: 222.2 47.4% 11.2%;
    --secondary: ${secondaryHSL};
    --secondary-foreground: 210 40% 98%;
    --muted: ${mutedHSL};
    --muted-foreground: 215 20.2% 65.1%;
    --accent: ${accentHSL};
    --accent-foreground: 210 40% 98%;
    --destructive: ${destructiveHSL};
    --destructive-foreground: 210 40% 98%;
    --success: ${successHSL};
    --success-foreground: 210 40% 98%;
    --warning: ${warningHSL};
    --warning-foreground: 222.2 84% 4.9%;
    --info: ${infoHSL};
    --info-foreground: 210 40% 98%;
    --border: ${borderHSL};
    --input: ${borderHSL};
    --ring: ${primaryHSL};
  }

  * {
    @apply border-border;
  }

  body {
    @apply bg-background text-foreground;
    font-family: ${fontFamily}, system-ui, -apple-system, sans-serif;
  }

  h1 {
    @apply text-4xl md:text-5xl font-[${headingWeight}] tracking-tight;
  }

  h2 {
    @apply text-3xl md:text-4xl font-[${headingWeight}] tracking-tight;
  }

  h3 {
    @apply text-2xl md:text-3xl font-[${headingWeight}];
  }

  h4 {
    @apply text-xl md:text-2xl font-semibold;
  }

  h5 {
    @apply text-lg md:text-xl font-semibold;
  }

  h6 {
    @apply text-base md:text-lg font-semibold;
  }

  p {
    @apply text-base leading-relaxed;
  }

  small {
    @apply text-sm;
  }
}

@layer components {
  /* Button Components */
  .btn {
    @apply inline-flex items-center justify-center text-sm font-medium transition-all;
    @apply focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2;
    @apply disabled:opacity-50 disabled:pointer-events-none;
    border-radius: ${radiusValue};
  }

  .btn-primary {
    @apply bg-primary text-primary-foreground hover:bg-primary/90;
  }

  .btn-secondary {
    @apply bg-secondary text-secondary-foreground hover:bg-secondary/80;
  }

  .btn-outline {
    @apply border-2 border-primary bg-transparent text-primary hover:bg-primary hover:text-primary-foreground;
  }

  .btn-ghost {
    @apply bg-transparent hover:bg-muted text-foreground;
  }

  .btn-sm {
    @apply h-8 px-3 text-xs;
  }

  .btn-md {
    @apply h-10 px-4 py-2;
  }

  .btn-lg {
    @apply h-12 px-6 text-base;
  }

  .btn-xl {
    @apply h-14 px-8 text-lg;
  }

  /* Card Components */
  .card {
    @apply border bg-card text-card-foreground shadow-sm;
    border-radius: ${radiusValue};
  }

  .card-hover {
    @apply transition-all duration-200 hover:shadow-md;
  }

  .card-interactive {
    @apply cursor-pointer transition-all duration-200 hover:shadow-lg hover:-translate-y-0.5;
  }

  .card-gradient {
    @apply bg-gradient-to-br from-card to-muted;
  }

  .card-padding {
    @apply p-6;
  }

  .card-padding-lg {
    @apply p-8;
  }

  /* Spacing Containers */
  .container {
    @apply max-w-7xl mx-auto px-4 md:px-6 lg:px-8;
  }

  .container-sm {
    @apply max-w-4xl mx-auto px-4 md:px-6;
  }

  .container-lg {
    @apply max-w-[1400px] mx-auto px-4 md:px-8;
  }

  .section {
    @apply py-16 md:py-24;
  }

  .section-sm {
    @apply py-12 md:py-16;
  }

  .section-lg {
    @apply py-24 md:py-32;
  }

  /* Grid Layouts */
  .grid-2 {
    @apply grid grid-cols-1 md:grid-cols-2 gap-6;
  }

  .grid-3 {
    @apply grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6;
  }

  .grid-4 {
    @apply grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6;
  }

  .grid-auto-fit {
    @apply grid gap-6;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  }

  /* Flexbox Utilities */
  .flex-between {
    @apply flex items-center justify-between;
  }

  .flex-center {
    @apply flex items-center justify-center;
  }

  .flex-start {
    @apply flex items-center justify-start;
  }

  .flex-end {
    @apply flex items-center justify-end;
  }

  .flex-col-center {
    @apply flex flex-col items-center justify-center;
  }

  /* Form Components */
  .form-group {
    @apply space-y-2;
  }

  .form-grid {
    @apply grid gap-4;
  }

  .form-grid-2 {
    @apply grid grid-cols-1 md:grid-cols-2 gap-4;
  }

  .form-grid-3 {
    @apply grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4;
  }

  .form-group input,
  .form-group textarea,
  .form-group select {
    @apply w-full px-3 py-2 border border-border bg-background;
    @apply focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent;
    @apply transition-all;
    border-radius: ${radiusValue};
  }

  /* Badge Components */
  .badge {
    @apply inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold transition-colors;
  }

  .badge-primary {
    @apply bg-primary text-primary-foreground;
  }

  .badge-success {
    @apply bg-success text-success-foreground;
  }

  .badge-destructive {
    @apply bg-destructive text-destructive-foreground;
  }

  .badge-sm {
    @apply px-2 py-0.5 text-[10px];
  }

  .badge-md {
    @apply px-2.5 py-0.5 text-xs;
  }

  .badge-lg {
    @apply px-3 py-1 text-sm;
  }

  /* Typography Utilities */
  .text-hero {
    @apply text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight;
  }

  .text-display {
    @apply text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight;
  }

  .text-heading {
    @apply text-2xl md:text-3xl font-semibold tracking-tight;
  }

  .text-subheading {
    @apply text-lg md:text-xl font-medium text-muted-foreground;
  }

  .text-gradient {
    @apply bg-clip-text text-transparent bg-gradient-to-r from-primary to-accent;
  }

  /* Shadow Utilities */
  .shadow-soft {
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  }

  .shadow-medium {
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.12);
  }

  .shadow-strong {
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.16);
  }
}${
    animations.intensity !== 'none'
      ? `

@layer utilities {
  @keyframes fade-in {
    from { opacity: 0; }
    to { opacity: 1; }
  }

  @keyframes slide-up {
    from {
      transform: translateY(20px);
      opacity: 0;
    }
    to {
      transform: translateY(0);
      opacity: 1;
    }
  }

  @keyframes scale-in {
    from {
      transform: scale(0.95);
      opacity: 0;
    }
    to {
      transform: scale(1);
      opacity: 1;
    }
  }

  @keyframes fade-in-up {
    from {
      opacity: 0;
      transform: translateY(20px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  @keyframes fade-in-down {
    from {
      opacity: 0;
      transform: translateY(-20px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  @keyframes pulse-ring {
    0% {
      transform: scale(1);
      opacity: 1;
    }
    100% {
      transform: scale(1.5);
      opacity: 0;
    }
  }

  @keyframes shake {
    0%, 100% { transform: translateX(0); }
    25% { transform: translateX(-4px); }
    75% { transform: translateX(4px); }
  }${
    animations.intensity === 'heavy'
      ? `

  @keyframes slide-in-left {
    from {
      transform: translateX(-30px);
      opacity: 0;
    }
    to {
      transform: translateX(0);
      opacity: 1;
    }
  }

  @keyframes slide-in-right {
    from {
      transform: translateX(30px);
      opacity: 0;
    }
    to {
      transform: translateX(0);
      opacity: 1;
    }
  }`
      : ''
  }

  .animate-fade-in {
    animation: fade-in 0.5s ease-in;
  }

  .animate-slide-up {
    animation: slide-up 0.3s ease-out;
  }

  .animate-scale-in {
    animation: scale-in 0.2s ease-out;
  }

  .animate-fade-in-up {
    animation: fade-in-up 0.6s ease-out;
  }

  .animate-fade-in-down {
    animation: fade-in-down 0.6s ease-out;
  }

  .animate-shake {
    animation: shake 0.5s ease-in-out;
  }${
    animations.intensity === 'heavy'
      ? `

  .animate-slide-in-left {
    animation: slide-in-left 0.4s ease-out;
  }

  .animate-slide-in-right {
    animation: slide-in-right 0.4s ease-out;
  }

  .delay-75 {
    animation-delay: 75ms;
  }

  .delay-100 {
    animation-delay: 100ms;
  }

  .delay-150 {
    animation-delay: 150ms;
  }

  .delay-200 {
    animation-delay: 200ms;
  }

  .delay-300 {
    animation-delay: 300ms;
  }

  /* Advanced animations for heavy mode */
  @keyframes bounce-in {
    0% { transform: scale(0.3); opacity: 0; }
    50% { transform: scale(1.05); }
    70% { transform: scale(0.9); }
    100% { transform: scale(1); opacity: 1; }
  }

  @keyframes wiggle {
    0%, 100% { transform: rotate(0deg); }
    25% { transform: rotate(-3deg); }
    75% { transform: rotate(3deg); }
  }

  .animate-bounce-in {
    animation: bounce-in 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55);
  }

  .animate-wiggle {
    animation: wiggle 0.5s ease-in-out;
  }`
      : ''
  }

  /* Gradient utilities */
  .bg-gradient-primary {
    background: linear-gradient(135deg, hsl(var(--primary)) 0%, hsl(var(--accent)) 100%);
  }

  .bg-gradient-secondary {
    background: linear-gradient(135deg, hsl(var(--secondary)) 0%, hsl(var(--muted)) 100%);
  }

  .text-gradient {
    background: linear-gradient(135deg, hsl(var(--primary)) 0%, hsl(var(--accent)) 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }

  /* Micro-interactions */
  .btn-press:active {
    transform: scale(0.98);
    transition: transform 0.1s;
  }

  .card-lift {
    transition: all 0.2s ease-out;
  }

  .card-lift:hover {
    transform: translateY(-4px);
    box-shadow: 0 12px 24px -8px rgba(0, 0, 0, 0.15);
  }

  input:focus, textarea:focus, select:focus {
    outline: none;
    box-shadow: 0 0 0 3px hsl(var(--primary) / 0.1);
    transition: box-shadow 0.2s;
  }

  /* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
     COMPREHENSIVE UTILITY SYSTEM
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */

  /* Button System */
  .btn {
    @apply inline-flex items-center justify-center rounded-xl font-medium transition-all duration-200;
    @apply disabled:opacity-50 disabled:cursor-not-allowed;
  }

  .btn-sm { @apply px-3 py-1.5 text-sm; }
  .btn-md { @apply px-4 py-2 text-base; }
  .btn-lg { @apply px-6 py-3 text-lg; }
  .btn-xl { @apply px-8 py-4 text-xl; }

  .btn-primary {
    @apply bg-primary text-primary-foreground hover:opacity-90 active:scale-95;
  }

  .btn-secondary {
    @apply bg-secondary text-secondary-foreground hover:bg-secondary/80;
  }

  .btn-accent {
    @apply bg-accent text-accent-foreground hover:opacity-90;
  }

  .btn-success {
    @apply bg-success text-success-foreground hover:opacity-90;
  }

  .btn-destructive {
    @apply bg-destructive text-destructive-foreground hover:opacity-90;
  }

  .btn-outline {
    @apply border-2 border-primary text-primary bg-transparent hover:bg-primary hover:text-primary-foreground;
  }

  .btn-ghost {
    @apply bg-transparent hover:bg-accent hover:text-accent-foreground;
  }

  .btn-icon {
    @apply p-2 aspect-square;
  }

  /* Spacing System */
  .section-sm { @apply py-8 md:py-12; }
  .section { @apply py-16 md:py-24; }
  .section-lg { @apply py-24 md:py-32; }
  .section-xl { @apply py-32 md:py-40; }

  .container-sm { @apply max-w-4xl mx-auto px-4 md:px-6; }
  .container { @apply max-w-7xl mx-auto px-4 md:px-6 lg:px-8; }
  .container-lg { @apply max-w-[1600px] mx-auto px-6 md:px-8 lg:px-12; }

  .card-padding-sm { @apply p-4; }
  .card-padding { @apply p-6; }
  .card-padding-lg { @apply p-8; }
  .card-padding-xl { @apply p-10 md:p-12; }

  /* Card System */
  .card {
    @apply bg-card border border-border rounded-xl;
  }

  .card-hover {
    @apply card transition-all duration-200 hover:shadow-lg hover:-translate-y-1;
  }

  .card-interactive {
    @apply card-hover cursor-pointer active:scale-[0.98];
  }

  .card-gradient {
    @apply card bg-gradient-to-br from-primary/10 to-accent/10 border-primary/20;
  }

  /* Form System */
  .form-group {
    @apply space-y-2;
  }

  .form-grid {
    @apply grid gap-4 md:gap-6;
  }

  .form-grid-2 {
    @apply grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6;
  }

  .form-grid-3 {
    @apply grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6;
  }

  input[type="text"],
  input[type="email"],
  input[type="password"],
  input[type="search"],
  input[type="number"],
  input[type="tel"],
  input[type="url"],
  input[type="date"],
  textarea,
  select {
    @apply w-full px-3 py-2 border border-border rounded-xl;
    @apply bg-background text-foreground;
    @apply focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent;
    @apply transition-all duration-200;
    @apply disabled:opacity-50 disabled:cursor-not-allowed;
  }

  textarea {
    @apply min-h-[100px] resize-y;
  }

  /* Badge System */
  .badge {
    @apply inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium;
  }

  .badge-sm { @apply px-2 py-0.5 text-xs; }
  .badge-md { @apply px-2.5 py-0.5 text-sm; }
  .badge-lg { @apply px-3 py-1 text-base; }

  .badge-primary {
    @apply bg-primary/10 text-primary border border-primary/20;
  }

  .badge-secondary {
    @apply bg-secondary/10 text-secondary-foreground border border-secondary/20;
  }

  .badge-success {
    @apply bg-success/10 text-success border border-success/20;
  }

  .badge-destructive {
    @apply bg-destructive/10 text-destructive border border-destructive/20;
  }

  .badge-warning {
    @apply bg-warning/10 text-warning border border-warning/20;
  }

  .badge-info {
    @apply bg-info/10 text-info border border-info/20;
  }

  /* Grid Patterns */
  .grid-auto-fit {
    @apply grid gap-6;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  }

  .grid-auto-fill {
    @apply grid gap-6;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  }

  .grid-2 {
    @apply grid grid-cols-1 md:grid-cols-2 gap-6;
  }

  .grid-3 {
    @apply grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6;
  }

  .grid-4 {
    @apply grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6;
  }

  /* Flex Patterns */
  .flex-between {
    @apply flex items-center justify-between;
  }

  .flex-center {
    @apply flex items-center justify-center;
  }

  .flex-start {
    @apply flex items-center justify-start;
  }

  .flex-end {
    @apply flex items-center justify-end;
  }

  .flex-col-center {
    @apply flex flex-col items-center justify-center;
  }

  /* Typography */
  .text-hero {
    @apply text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight;
  }

  .text-display {
    @apply text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight;
  }

  .text-heading {
    @apply text-3xl md:text-4xl font-bold tracking-tight;
  }

  .text-subheading {
    @apply text-2xl md:text-3xl font-semibold;
  }

  .text-section {
    @apply text-xl md:text-2xl font-semibold;
  }

  .text-body-lg {
    @apply text-lg leading-relaxed;
  }

  .text-body {
    @apply text-base leading-relaxed;
  }

  .text-small {
    @apply text-sm text-muted-foreground;
  }

  .text-gradient {
    @apply bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent;
  }

  /* Shadows */
  .shadow-soft {
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05), 0 1px 2px rgba(0, 0, 0, 0.03);
  }

  .shadow-medium {
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.05);
  }

  .shadow-strong {
    box-shadow: 0 10px 15px rgba(0, 0, 0, 0.1), 0 4px 6px rgba(0, 0, 0, 0.05);
  }

  .shadow-xl-colored {
    box-shadow: 0 20px 25px -5px rgba(var(--primary), 0.15), 0 10px 10px -5px rgba(var(--primary), 0.04);
  }

  /* Animation Utilities */
  .stagger-item {
    @apply opacity-0;
    animation: fade-in 0.5s ease-out forwards;
  }

  .stagger-item:nth-child(1) { animation-delay: 0.05s; }
  .stagger-item:nth-child(2) { animation-delay: 0.1s; }
  .stagger-item:nth-child(3) { animation-delay: 0.15s; }
  .stagger-item:nth-child(4) { animation-delay: 0.2s; }
  .stagger-item:nth-child(5) { animation-delay: 0.25s; }
  .stagger-item:nth-child(6) { animation-delay: 0.3s; }
  .stagger-item:nth-child(7) { animation-delay: 0.35s; }
  .stagger-item:nth-child(8) { animation-delay: 0.4s; }

  .hover-lift {
    @apply transition-all duration-200;
  }

  .hover-lift:hover {
    @apply -translate-y-1 shadow-lg;
  }

  .hover-glow:hover {
    box-shadow: 0 0 20px rgba(var(--primary), 0.3);
  }

  .hover-scale {
    @apply transition-transform duration-200;
  }

  .hover-scale:hover {
    @apply scale-105;
  }

  @keyframes shimmer {
    0% { background-position: -1000px 0; }
    100% { background-position: 1000px 0; }
  }

  .shimmer {
    background: linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.2) 50%, transparent 100%);
    background-size: 1000px 100%;
    animation: shimmer 2s infinite;
  }

  @keyframes pulse-slow {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.7; }
  }

  .pulse-slow {
    animation: pulse-slow 3s cubic-bezier(0.4, 0, 0.6, 1) infinite;
  }
}`
      : ''
  }
`;
  console.log('[Frontend] ✅ globals.css directly generated - skipping AI');
  console.log(`[Frontend] 🎯 Template length: ${globalsCss.length} characters`);
  console.log(`[Frontend] 🎯 Has @layer components: ${globalsCss.includes('@layer components')}`);
  console.log(`[Frontend] 🎯 Has .btn class: ${globalsCss.includes('.btn {')}`);
  console.log(`[Frontend] 🎯 Has .card class: ${globalsCss.includes('.card {')}`);
  console.log(`[Frontend] 🎯 Animation intensity: ${animations.intensity}`);
  console.log(`[Frontend] 🎯 First 1000 chars:\n${globalsCss.substring(0, 1000)}`);
  return globalsCss;
}
